spring:
  application:
    name: supplier-hub

  config:
    import: optional:file:./.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/supplier_hub}
    username: ${DB_USERNAME:supplier_hub}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  web:
    resources:
      add-mappings: true

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health, info
