package com.supplierhub.supplier.common;

public enum SupplierFailureType {

	INVALID_REQUEST,
	AUTHENTICATION_FAILED,
	RATE_LIMITED,
	UNAVAILABLE,
	TIMEOUT,
	INVALID_RESPONSE,
	CATALOG_UNAVAILABLE,
	UNKNOWN

}
