CREATE TABLE supplier_property (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier VARCHAR(32) NOT NULL,
    supplier_property_code VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_supplier_property_supplier_code
        UNIQUE (supplier, supplier_property_code)
);

CREATE TABLE supplier_room_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL,
    supplier_room_type_code VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    max_occupancy INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_supplier_room_type_property
        FOREIGN KEY (property_id) REFERENCES supplier_property (id),
    CONSTRAINT uq_supplier_room_type_property_code
        UNIQUE (property_id, supplier_room_type_code),
    CONSTRAINT ck_supplier_room_type_max_occupancy
        CHECK (max_occupancy > 0)
);

CREATE INDEX ix_supplier_property_active_supplier
    ON supplier_property (active, supplier);

CREATE INDEX ix_supplier_room_type_active_property
    ON supplier_room_type (active, property_id);
